### ISSUE TITLE
Local store + Index

### ISSUE THREAD

**Issue by parkan** [mediachain/concat#10]
Local store for statements and index

Probably SQLite but maybe something like rocksdb

Do we need to consider long-term/large dataset storage optimizations at all yet?

**Comment by vyzo** [comment]
SQLite should be sufficient for the immediate future. 
I don't think rocks.db is a good choice here (except perhaps for raw statement storage); we need an index and query capabilities.

In terms of scaling, SQLite can takes us far enough I think, and it should be easy to swap in a more heavyweight db solution if/when the need arises.

**Comment by parkan** [comment]
What protocol level metadata are we thinking about? Signer, timestamp, what else?

Down with SQLite, but should keep the scaling to billions of rows/batch processing/potentially columnar store case in mind.

**Comment by vyzo** [comment]
As a baseline I think we need indexing by namespace, id, publisher, timestamp, tags, and WKI references.

Well, the plan is to have it simple to use for lightweight usage. 
For aggregators/big nodes we will probably want to use a database server or RDS.
