### ISSUE TITLE
mcid UX

### ISSUE THREAD

**Issue by parkan** [mediachain/concat#121]
Some things should be a bit smoother about the registration flow:

* `mcid sign` will accept arbitrary strings as identities

Should ensure correct format (`provider:id`) and either A) ensure provider is supported or B) automatically verify. I can see an argument against B if we want to support offline signing, maybe put this behind a flag to disable.

* `mcid verify` output should be more helpful

Right now the error is `Error looking up entity key: Entity key not found`, which is unclear about what is actually missing. Should ideally report whether the *ENTITY* is missing (i.e. no keybase/blockstack profile by that name) or the *KEY FILE* is missing. At minimum, should say something like `"Ensure that $provider:identity is regsitered and that mediachain identity is published"`

* "Enter Passphrase" during signing is a bit unclear

To me at least it wasn't 100% clear that this was the mc identity passphrase, seems like it could also have been a key for whatever provider you're signing for

**Comment by vyzo** [comment]
A couple of thoughts:
- We don't need automatic verification in sign -- what we need is to make sure that our key is accessible through the identity specified. I am not convinced this should be a default behaviour though, as it significantly slows down the workflow and is vulnerable to provider availability issues (the blockstack client can be both slow and unreliable). Besides, we can always manually check with a subsequent verify.
- I think the passphrase ux flow is correct; it is an operation that requires the private key, and hence it asks for a passphrase. It would be rude to ask for a passphrase for anything other than the managed key, so I don't think that needs to change.

**Comment by parkan** [comment]
> We don't need automatic verification in sign -- what we need is to make sure that our key is accessible through the identity specified. I am not convinced this should be a default behaviour though, as it significantly slows down the workflow and is vulnerable to provider availability issues (the blockstack client can be both slow and unreliable). Besides, we can always manually check with a subsequent verify.

Yeah, fair enough. Should still make sure format and prefix are valid though, since that's cheap

> I  think the passphrase ux flow is correct; it is an operation that requires the private key, and hence it asks for a passphrase. It would be rude to ask for a passphrase for anything other than the managed key, so I don't think that needs to change.

Many rude things happen, but I can live with this too

**Comment by vyzo** [comment]
> Yeah, fair enough. Should still make sure format and prefix are valid though, since that's cheap

Of course; that goes without saying :)

> Many rude things happen, but I can live with this too

I'd like to believe that our software is not rude!
