### ISSUE TITLE
Push Publishing for trusted sources

### ISSUE THREAD

**Issue by vyzo** [mediachain/concat#23]
Implement the mediachain/node/push protocol to allow trusted publishers to push statements to stable nodes.

Requires #12 to implement.

**Comment by parkan** [comment]
This will be very useful for paired alephs, should be relatively simple to impl via node-local whitelist

**Comment by vyzo** [comment]
This is blocked until we have usable ECC keys in js side for signing statements.

**Comment by vyzo** [comment]
It is actually usable without aleph signing support: we can use it to support public writes to stable nodes.
So a pure concat-concat push is possible.

Re-enstating to v1.2.
