### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by parkan** [mediachain/concat#3]
This can probably live as a part of this project. Simple python (?) tool to control the peer node, can probably reuse pieces of https://github.com/mediachain/mediachain-client

**Comment by vyzo** [comment]
This depends on the API in #2, but at any rate it should be language independent.

**Comment by vyzo** [comment]
I think curl will do for testing and lightweight usage.
For better UX we can have a js client common for both concat and aleph.

**Comment by parkan** [comment]
Agreed, at this point a text file with a few curl commands (which nevertheless should be included in the repo) will do

Beyond that, js is the way, I think

**Comment by vyzo** [comment]
Aleph it is.
