### ISSUE TITLE
Read benchmarks

### ISSUE THREAD

**Issue by parkan** [mediachain/concat#32]
Would like to see numbers for 
- Raw SQLite reads, streaming/batched (let's say batches of 200-600)
- RocksDB reads
- concat reads, streaming/batched (would need to implement multiread #31)

**Comment by autoencoder** [comment]
Perhaps also random reads, on a 100M to 500M record DB, after running

 `echo 1 | sudo tee /proc/sys/vm/drop_caches`

 :)

**Comment by parkan** [comment]
Seeing satisfactory performance here, closing for now
