### ISSUE TITLE
Metadata store

### ISSUE THREAD

**Issue by parkan** [mediachain/concat#36]
KV store for actual metadata objects. Should conform to the [go-datastore](https://github.com/ipfs/go-datastore) interface so IPFS can read from it. Will also serve as the "document store" for the indexer. Can be backed by e.g. LMDB though I suspect @autoencoder has thoughts on this

Closes #33

**Comment by vyzo** [comment]
I think implementing that interface is really an unreasonable amount of complexity, as we discussed.

So let's use a embedded kvdb with a narrow Put/Get/Delete interface.
