### ISSUE TITLE
Secondary indexes

### ISSUE THREAD

**Issue by parkan** [mediachain/concat#39]
Need secondary indexes for:
 
- WKIs (possibly compound index/additional table because these are in 2-part `prefix:id` format)
- tags: e.g. `images`, `CC`, etc -- folksonomy, arbitrary strings
- refs [LATER]

**Comment by vyzo** [comment]
The important one to index is the WKI, as it's a user identifier.
Not sure if we should index tags yet, as there might be significant space overhead, as well as slow queries.

#51 implements adds join index support in MCQL and provides an index for WKIs.

Note that an artefact of the implementation is that we can do a wki AND wki query to select statements which jointly refer to some wkis, but that's of marginal utility and it's acceptable not to support it for performance reasons.
