### ISSUE TITLE
Public "PR" mechanism

### ISSUE THREAD

**Issue by parkan** [mediachain/concat#42]
This is one potential mechanism for data set aggregation: prompt a remote operator to merge in some statements from your node. Can probably take the form of a web UI that shows the changeset (+ potentially any conflicts) and lets the user merge that set through the normal mechanisms.

This is a nice, shareable way to get users to interact with the system and potentially supplements whatever other aggregation mechanisms we choose to use.

Complements #23 for less trusted sources.

**Comment by denisnazarov** [comment]
I like this idea 👍

**Comment by parkan** [comment]
Semantics of whether or not this crosses namespace boundary is tbd

@vyzo what do you think?

**Comment by vyzo** [comment]
Maybe we can do that, but it may better belong to aleph in terms of UX.

**Comment by parkan** [comment]
Agreed, gonna move to that repo 😄
