### ISSUE TITLE
UX enhancements

### ISSUE THREAD

**Issue by vyzo** [mediachain/concat#43]
It's an assortment of usability enhancments from my worklog todo tags, that will definitely improve the out of the box experience of using concat (and aleph).

- [X] Stopping default to `/tmp/mcnode` for node home, use something like `~/.mediachain/mcnode`
- [X] Add auto IP detection in manual port-mappings, to better support transparent firewalls and multi-NAT situations.
  The manual NATConfig config option can be:
   - `*` uses the locally bound port, with auto-detected IP address
   - `*:port` uses the specified port with auto-detected IP address
   - `ip:port` is the consistent way to pass ip addresses, ditch the ugly multiaddr
- [X] Add a hook to retrieve all known routable addresses, including the auto-detected public NAT, regardless of directory view point. 
- [X] Add a `/shutdown` hook for flushing and closing the dbs for clean node shutdown
- [X] Implement the basic list directory protocol, which will allow users to discover nodes and run some queries.
- [X] Add a configurable option for public info describing or identifying the node. 
- [ ] Add a hook to add routing for peers, so that we can connect to them without a directory if we know their handle.
  The routing cache should be sticky and survive restarts
- [ ] Support multiple directories. This will allow nodes to register with private directories as well as public directories, and provide the correct ip bindings for different network vantage points (lan, vpc -vs- Internet)

**Comment by parkan** [comment]
I think this is a mix of stuff we want in V2 and maybe V3/V4. Main one is setting a sensible default dir.

**Comment by vyzo** [comment]
I think we are good for v1.0 release; the remaining two points can be defered for now.
