### ISSUE TITLE
Schema versioning

### ISSUE THREAD

**Issue by parkan** [mediachain/concat#49]
Would be nice to figure this out ASAP so this early import data can continue to coexist with later data and be summarily ignored due to outdated schema version (i.e. avoid total universe wipe)

Probably based on snowplow's [semver for schemas](http://snowplowanalytics.com/blog/2014/05/13/introducing-schemaver-for-semantic-versioning-of-schemas/)

**Comment by parkan** [comment]
@yusefnapora this actually belongs in aleph I guess

**Comment by vyzo** [comment]
yeah, let's move it over; closing.
