### ISSUE TITLE
Release process for compiled builds

### ISSUE THREAD

**Issue by yusefnapora** [mediachain/concat#56]
We should set up an automated build process that compiles tagged releases for linux and osx.  This should be possible on Travis: https://docs.travis-ci.com/user/deployment/releases

Their mac os environments support go 1.7, so we should be good there.

TODO: 
- [X] setup travis matrix build for linux and osx environments
- [X] cache the big dependencies (gorocksdb, the gx stuff, etc)
- [X] configure travis to push tagged releases to github

**Comment by denisnazarov** [comment]
Would be awesome to do this before launch. Installing gorocksdb took 10min+ on my laptop and really made going through the tutorial sad :\

cc @parkan

**Comment by yusefnapora** [comment]
we can at least manually upload binaries until we get things automated

**Comment by parkan** [comment]
Oh yeah let's cook some binaries, this should have been on the list

**Comment by vyzo** [comment]
We can also do container based setup -- the base container with the dependencies and build on top should be fast.

At any rage, let's have a fast installation procedure I can add to the README -- in fact I'll make a couple of sections and start with them (and have installation from source last, with the caveat that it is slow!)

**Comment by vyzo** [comment]
Also for binaries: I can make and sign binaries for linux and yusef can do the same for OSX.
We need a place to put them though.

**Comment by parkan** [comment]
Don't need to get this in for V2, however see https://github.com/mediachain/concat/issues/59

**Comment by vyzo** [comment]
Implemented in #61
