### ISSUE TITLE
Tag+upload 1.0 release

### ISSUE THREAD

**Issue by parkan** [mediachain/concat#59]
Doesn't need to be automated, just needs to have a build here: https://github.com/mediachain/concat/releases

**Comment by vyzo** [comment]
Let's merge in #59, and we can create the release and attach binaries by hand.

**Comment by vyzo** [comment]
Relase binaries: `mcnode-{platform}.gz mcdir-{platform}.gz`
where platform is `linux-amd64` or `darwin-amd64`, which is what we can build by hand easily.
I don't think we should have the version number there, that's implied by the release.

**Comment by vyzo** [comment]
v1.0 tagged and published.
