### ISSUE TITLE
Installing from source fails on Windows 10

### ISSUE THREAD

**Issue by edsilv** [mediachain/concat#65]
```
Installing unvendored deps
# github.com/mattn/go-sqlite3
exec: "gcc": executable file not found in %PATH%
FAILED
```

related? https://github.com/mattn/go-sqlite3/issues/214

**Comment by vyzo** [comment]
We use cgo for sqlite and rocksdb, so that means you need gcc and g++ -- and yes, that's the same issue for sqlite.

Unfortunately none of us has any windows computers, so we haven't been able to test there. If you can get it to build we'll be happy to add a section in the README for building on windows.

**Comment by edsilv** [comment]
tried this: https://github.com/mattn/go-sqlite3/issues/214#issuecomment-244604166

had to manually select the x64 option.

now getting this:

```
Installing unvendored deps
Installing gorocksdb; this can take a while!
# github.com/cockroachdb/c-jemalloc
..\..\cockroachdb\c-jemalloc\arena.c:1:9: error: expected '=', ',', ';', 'asm' or '__attribute__' before '/' token
 internal/src/arena.c
         ^
# github.com/cockroachdb/c-lz4
..\..\cockroachdb\c-lz4\lz4.c:1:9: error: expected '=', ',', ';', 'asm' or '__attribute__' before '/' token
 internal/lib/lz4.c
         ^
# github.com/cockroachdb/c-snappy
..\..\cockroachdb\c-snappy\snappy-c.cc:1:1: error: 'internal' does not name a type
 internal/snappy-c.cc
 ^~~~~~~~
FAILED

```

**Comment by vyzo** [comment]
this looks like it might be some c++ std version support issue? Maybe it needs a more recent g++ or some std specific option.

@yusefnapora can you give a shot at building on a windows vm?

**Comment by yusefnapora** [comment]
yeah, I'm trying to get my windows vm into shape now.  it's possible that we might need to build rocksdb separately on windows and not use the `embed` tag.  I'll try to sort it out :)

**Comment by parkan** [comment]
hey edsilv are you using the latest mingw64?

**Comment by edsilv** [comment]
@parkan think so... downloaded from here: https://sourceforge.net/projects/mingw-w64/

**Comment by vyzo** [comment]
README has been upgraded to provide instructions for running with the linux binaries.

Keeping the issue open, as we eventually have to figure out building from source on windows.

**Comment by parkan** [comment]
@edsilv closing this, let me know if you're still having trouble
