### ISSUE TITLE
Don't require changing metadata object to specify WKI

### ISSUE THREAD

**Issue by denisnazarov** [mediachain/concat#70]
Thinking through WKI specification while trying to write a [tutorial for writing MoMA data](https://gist.github.com/denisnazarov/f990f0e7367b38afa2bad351ee26d9a9) (credit to @yusefnapora ). It would be great to completely remove all the steps where you modify the original data.

We shouldn't require publishers to change their data to specify a WKI. Currently in our examples we're either adding prefixes to IDs (`dpla_abc123`) or new object keys (`MediachainWKI: "moma:artist:123""`from [the guide](https://gist.github.com/denisnazarov/f990f0e7367b38afa2bad351ee26d9a9)).

It would be elegant if publishers could keep their original metadata object completely untouched, giving nice properties such as keeping the same multihash if they're using the raw object somewhere else (like IPFS).

Can WKI prefixes be stored outside of the object? We already have a unique prefix we can automatically use: the namespace. Is this enough to avoid id collisions since, for example, MoMA uses integer IDs for artists and artworks.

We should also include searching by WKI more prominently in the docs!

**Comment by vyzo** [comment]
The wki's come from the ingesting client, open this issue on aleph instead?
In general I agree that we should strive to keep the origin ids; our current nodes use what came with the dataset from the indexer.
