### ISSUE TITLE
Support multiple directories in mcnode

### ISSUE THREAD

**Issue by vyzo** [mediachain/concat#77]
Currently mcnode only supports a single directory; that makes me sad.

**Comment by parkan** [comment]
Should clarify this ASAP with our thinking on the network topology and the role of directories

**Comment by denisnazarov** [comment]
Would like to include Blockstack in this discussion and decide on its role in roadmap.. IMO better to have one canonical, decentralized directory than enabling fracturing of discovery (although see the value of ppl being able to make their own dirs)

**Comment by parkan** [comment]
Clarification of @denisnazarov's comment based on verbal discussion: what is being suggested is using blockstack as a synchronization feed for Universe namespace mappings. 

Something like:

* When registering an identity on blockstack (or when updating it) you can also specify namespaces that you wish to announce
* Directory servers listen to blockstack updates and update their local namespace:[peerId] mappings in /u/
* Clients route queries appropriately

This could also be accomplished by building our own gossip network, but this approach has the advantage of using the existing blockstack infrastructure, builtin pay-to-register (we could potentially have relatively complex registration rules, need to discuss w/ryan) and convenient colocation of identity and discovery.

**Comment by parkan** [comment]
Another possibility is having multiple *blockstack namespaces*, for ex. /mc-u/ is universe with very low registration costs, /mc-omi/ is for industry and has v high reg cost, etc.

**Comment by parkan** [comment]
Seems that we can potentially use existing IPFS `findPeer` functionality to map peerIds to IPs: https://github.com/ipfs/go-ipfs/blob/6779ff10217f7c97d98e7ac68ca7c6c7efe6a809/routing/supernode/client.go#L119

**Comment by vyzo** [comment]
@parkan @denisnazarov Re: blockstack as synchronization

Let's move this into its own separate issue? It's orthogonal to whether there is one or more directories.

**Comment by parkan** [comment]
@vyzo agreed, will move out to an issue codependent w/IPFS interop

**Comment by parkan** [comment]
Moved blockstack/directoryless mode discussion into #80
