### ISSUE TITLE
IPFS interop

### ISSUE THREAD

**Issue by parkan** [mediachain/concat#78]
Based on some additional thinking, we may want to pursue (limited) IPFS interop sooner rather than later.

In particular, registering our peers with the IPFS DHT will make them discoverable with `findPeer`, which will help cross-directory (or, potentially, directory-less) discovery. See #77 for some thoughts on this.

The actual "minimal interop" footprint is reasonably small:
- [X] Use p2p multiaddrs (see discussion [here](https://github.com/multiformats/multiaddr/pull/27), TLDR is that our addrs should look like `/ip4/99.69.16.78/tcp/4001/p2p/QmfWapjgngSkeaA5B34YaYGdVPNocUP72hMoCmosdJVzoK`)
- [X] Specify the `agentVersion` in our `Identify` 
-  Specify protocols -- we already specify the `/mediachain/dir` protocols [here](https://github.com/mediachain/concat/blob/8527b48193ff5ba627cf9d55dde66f7b63ebc8b6/mcdir/main.go#L207), we would need to add `/ipfs/bitswap/1.1.0` to get `findPeer` (it seems like DHT is rolled into bitswap, but need to find out); edit: this is unnecessary, the protocols are automatically reported by libp2p in identify -- vyzo

The tricky part is this: I'm not sure how IPFS would feel about us being "moocher nodes" that only run findPeer queries and don't store anything (or if the protocol even supports this), so we may need to actually participate. This is a possible conversation topic?

I'm thinking that it may be best to add bitswap to the directories only so that `lookupPeer` API stays the same for the nodes but the directory can go out to the IPFS DHT to find a peer not registered with it for universe queries.

What do you think @yusefnapora @vyzo ?

**Comment by yusefnapora** [comment]
I feel like we do want to participate in bitswap to some extent, in that we want to support storing blobs on ipfs eventually, although I've been thinking that we'd do so at a higher level by delegating to the default ipfs tools...

 I don't know how much overhead is involved in playing nice with the main DHT, but it would be nice to use IPFS as a kind of service-discovery layer if possible... is it possible to advertise a protocol that you support to the IPFS DHT?  Then we could advertise that we handle the `/mediachain/dir` protocol, and / or nodes could advertise the protocols they handle, and the directory could periodically find them...

I think I need to mull this over a bit more before my opinions will be very useful 😄

**Comment by parkan** [comment]
@yusefnapora `findPeer` gives you an identity object (from the linked protobuf above) which has a AgentVersion and a ProtocolVersion (actually now looking at a real example my AgentVersion is `go-libp2p/0.1.0` and my ProtocolVersion is `ipfs/0.1.0`, which is the opposite of what I expected)

I am told that the AgentVersion should be identifying, and the protocols are verified during the multistream handshake. This doesn't seem well-exercised yet, but it is almost exactly the usecase we want.

/cc @jbenet

**Comment by parkan** [comment]
Actually, I was wrong, seems like findpeer gets back a list of multiaddresses only (though you can then go and id the nodes)

**Comment by vyzo** [comment]
We can't reasonably add bitswap as an advertised protocol, as we won't actually implement it (unless it's refactored out of ipfs).

**Comment by vyzo** [comment]
Also, there are simpler ways to do directory service discovery.
For instance, we can fetch it from a configured url -- so we can use directory.mediachain.io to find the handle for one or more directory nodes.

**Comment by vyzo** [comment]
In broad terms, there are a couple of things we want in long term interoperability:
- Ability to find peers through the DHT, so that we can be online and operate without a directory
- Transparent distribution of MC objects through ipfs (IPLD)

I think the first one can be reasonably implemented: we can integrate the kad-dht implementation and implement the necessary Identify protocols so that we can find nodes through the DHT. Although I am sure it wont be trivial and there will be gymnastics needed to accommodate  ipfs network specifics.

The second one is a complicated issue:
- we need to integrate a bitswap implementaiton, which needs to be modularized out of go-ipfs.
- we need to solve the (hard) provider record problem.

**Comment by vyzo** [comment]
Re: identity protocol
We are not currently binding any services from libp2p -- but it's easy to bind the libp2p ID service. 
Nonetheless, it doesn't offer any method to configure the agent string.

**Comment by parkan** [comment]
@vyzo I think we're basically in agreement here. Main thing to keep in mind is that adding DHT-based peer finding can really bolster our decentralization story, even if it's not the primary mode for now, so it's worth putting some work into it.

* The IPFS protocols are [defined here](https://github.com/libp2p/specs/blob/master/7-properties.md#757-protocol-multicodecs), couldn't find this page before. Looks like we just need `/ipfs/kad/1.0.0` on top of we already have (it wasn't clear if DHT was actually separated as a protocol before)
* Looks like actual DHT code has been successfully separated into https://github.com/libp2p/go-libp2p-kad-dht 😀 
* /p2p/ multiaddr change needs to go in for this to work (likely w/backwards compatibility to /ipfs/ on their end), but this is a small change (also see PR below)
* Chatting w/david about specifying version strings, sounds like it's kinda janky and needs fixing: https://github.com/multiformats/multiaddr/pull/27#issuecomment-259232310

Agreed that we don't need bitswap at this point, wasn't sure if DHT protocol was separate from it 🙂

**Comment by vyzo** [comment]
Initial IPFS DHT integration (using client mode for now) in #90

**Comment by whyrusleeping** [comment]
Any thoughts on supporting the ping protocol?

**Comment by vyzo** [comment]
Sure, is there an extant implementation we can reuse?
If we need to write an implementation (based perhaps on ipfs code), we can also write it directly in libp2p as a module.

**Comment by whyrusleeping** [comment]
Yeah, it should be in go-libp2p under p2p/protocol/ping

**Comment by vyzo** [comment]
ok, cool; we'll add support for it.

**Comment by vyzo** [comment]
#113 added support for the ping protocol, and also identifies our client version.
