### ISSUE TITLE
Advertise namespaces through blockstack

### ISSUE THREAD

**Issue by parkan** [mediachain/concat#80]
Moving discussion from #77, where it went way off topic.

Let's use blockstack as a synchronization feed for Universe namespace mappings. Something like:

* When registering an identity on blockstack (or when updating it) you can also specify namespaces that you wish to announce
* Directory servers listen to blockstack updates and update their local namespace:[peerId] mappings in /u/
* Clients route queries appropriately

This could also be accomplished by building our own gossip network, but this approach has the advantage of using the existing blockstack infrastructure, builtin pay-to-register (we could potentially have relatively complex registration rules, need to discuss w/ryan) and convenient colocation of identity and discovery.

A related possibility is having multiple blockstack namespaces, for ex. /mc-u/ is universe with very low registration costs, /mc-omi/ is for industry and has v high reg cost, etc.

NOTE: this will only give us peerIds, we will likely need #78 to get actual addresses from DHT.

**Comment by denisnazarov** [comment]
@parkan pls update w/ more thoughts on mvp integration after your prep for the blockstack meetup presentation 🌎

**Comment by parkan** [comment]
@denisnazarov this is p theoretical so moving to internal
