### ISSUE TITLE
Setup ifconfig server, with fallback to public service

### ISSUE THREAD

**Issue by vyzo** [mediachain/concat#83]
The IP auto-detection implementation utilizes a public ip lookup service: initially `ifconfig.me`, which proved unreliable, and as of #82 `ifconfig.co`.

The code behind `ifconfig.co` is available at https://github.com/martinp/ipd, so we can easily setup and run our own ifconfig server at `ifconfig.mediachain.io`.
We can then use it as primary, with fallback to the public server.

**Comment by parkan** [comment]
So just for fun I adapted ipd to be 1-click Heroku deployable and set up an instance at https://evening-journey-25199.herokuapp.com/

See https://github.com/parkan/ipd

Can setup an alias or w/e, presumably we want it to be https tho

**Comment by parkan** [comment]
Can drop in cert from letsencrypt or w/e for custom name too  https://blog.heroku.com/announcing_heroku_free_ssl_beta_and_flexible_dyno_hours

**Comment by vyzo** [comment]
i don't think we care about https for this.

**Comment by parkan** [comment]
@jessewalden can you CNAME ifconfig.mediachain.io to mediachain-ifconfig.herokuapp.com?

**Comment by vyzo** [comment]
Is this actually any more reliable than using ifconfig.co?

**Comment by parkan** [comment]
@vyzo at least if it fails, it is our fault

**Comment by parkan** [comment]
hmm though ifconfig.co is also on heroku so maybe not

**Comment by jessewalden** [comment]
done

**Comment by parkan** [comment]
```
[master//aleph]% curl ifconfig.mediachain.io
67.244.113.119
```

nice

**Comment by vyzo** [comment]
ok, will open a PR for using it.
