### ISSUE TITLE
Extended/structured node info

### ISSUE THREAD

**Issue by parkan** [mediachain/concat#99]
Related to #71, but should also be usable w/o directory

Node info is currently a freeform string, we should have some machine-readable fields in there, notably namespaces. Possibly also some kind of cryptographic proof of association with that namespace?

**Comment by vyzo** [comment]
I think the first step is to connect with an external identity; cf #14 
So the structured node info can start with a node identification manifest, which includes the peer id and the publisher id, signed by an application specific key for an entity id.
